language: node_js

node_js:
  - node

cache: yarn

script:
  - yarn lint
  - yarn test

deploy:
  provider: script
  script: yarn deploy:ci
  skip_cleanup: true
  on:
    branch: master

after_success:
  - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION
